### ISSUE TITLE
Worldserver spams "TC>", cannot connect to realm

### ISSUE THREAD

**Issue by qwoodmansee** [neechbear/trinitycore#14]
this is a follow up to #13 - After running `make run` the process runs for a few minutes and the docker containers start to spin up. Once the world server spins up it spams `TC>` never ending, and it fills the entire terminal.

I've attached screenshots of the terminal as it starts up. I am unsure what to do about this. Just for clarification, the auth server seems to be up (I can connect with `trinity` `trinity` from a game client,) and there are 2 realms listed (one greyed out, the second not), but I can't actually join the realm / create any characters.

https://imgur.com/a/W1v1V7R
^ Here are the images.

**Comment by pvormste** [comment]
Hello @qwoodmansee,
I was facing the same problems today and I got them fixed!

**1. worldserver spamming "TC>"**
You only need to disable the worldserver console.
Open the `artifacts/etc/worldserver.conf` and set the following entry:
`Console.Enable = 0`

Default is:
`Console.Enable = 1`

**2. Not able to connect to realm**
You have to connect to the mariadb and update the realmlist table like so:
`update realmlist set address='my.wowserver.com' where id=2;`

The address is set to `127.0.0.1` by default, which does not work when the server is not running on the same machine.

Hope it helps!

**Comment by qwoodmansee** [comment]
(my last comment was dumb, i accidentally messed up the sql update because i was using an unfamiliar GUI. I should have just stuck with the command line. Thanks for all your help)
