### ISSUE TITLE
Run issue

### ISSUE THREAD

**Issue by Malpractis** [neechbear/trinitycore#7]
Hey great work!

I've successfully complied using your docker containers. After that I assume I need to cd into the trinitycore folder and issue "make run"?

I'm getting an error in the worldserver build process.

ERROR: Service 'worldserver' failed to build: ADD failed: no source files were specified
Makefile:125: recipe for target 'run' failed
make: *** [run] Error 1

Ubuntu 16.04 LTS server

I've also tried manually compiling and running but am getting the same error.

Any help would be most appreciated.

**Comment by Malpractis** [comment]
Just rebuilt on a Debian 9 VM.

Compiled with docker.
Cloned the source from GIT.
Tried to run the docker-compose.yaml

It failed at:
Step 14/17 : ADD TDB_*.sql "${install_prefix}/bin/"

**Comment by qwoodmansee** [comment]
Did you manage to fix this @Malpractis ?

`
It failed at:
Step 14/17 : ADD TDB_*.sql "${install_prefix}/bin/"
`

my ubuntu 18.04 run attempt is failing at the same place
